version: '{branch}.{build}'
configuration: RelWithDebInfo
environment:
  global:
    VENV_DIR: "venv"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 15
      VCPKG_INTEGRATION: '-DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 12
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 10
install:
- pip install --upgrade setuptools
- cinst -y swig
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%
- vcpkg install jsoncpp:x86-windows
- vcpkg install jsoncpp:x64-windows
- vcpkg integrate install
- python -m pip install --user --upgrade pip
- "virtualenv --clear %VENV_DIR%"
- "%VENV_DIR%\\Scripts\\activate.bat"
- pip install --upgrade setuptools
- pip install tox
cache:
- C:\ProgramData\chocolatey\bin -> .appveyor.yml
- C:\ProgramData\chocolatey\lib -> .appveyor.yml
- C:\Tools\vcpkg\installed -> .appveyor.yml
before_build:
- mkdir BLD
- cd BLD
- cmake %VCPKG_INTEGRATION% -G "%CMAKE_GENERATOR%" %QPID_PROTON_CMAKE_ARGS% ..
- cd ..
build:
  project: BLD/Proton.sln
  parallel: true
  verbosity: normal
test_script:
- cd BLD
- cmake --build . --target install --config %CONFIGURATION%
- ctest -V -C %CONFIGURATION% %QPID_PROTON_CTEST_ARGS%
- cd ..
