version: '{branch}.{build}'
configuration: RelWithDebInfo
environment:
  global:
    VENV_DIR: "venv"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      PYTHON: 2.7
      VCPKG_INTEGRATION: '-DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
      VCPKG_DEFAULT_TRIPLET: x64-windows
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      PYTHON: 2.7
      VCPKG_INTEGRATION: '-DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
      VCPKG_DEFAULT_TRIPLET: x86-windows
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      PYTHON: 2.7
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      CMAKE_GENERATOR: Visual Studio 12 2013
#      PYTHON: 2.7
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
#      CMAKE_GENERATOR: Visual Studio 11 2012
#      PYTHON: 2.7
init:
- ps: Start-FileDownload 'http://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi' C:\VCForPython27.msi; echo "Done"
- cmd: msiexec /i C:\VCForPython27.msi /quiet /qn
install:
- pip install --upgrade setuptools
- cinst -y swig
# https://www.appveyor.com/docs/lang/cpp/#vc-packaging-tool
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%
- vcpkg install jsoncpp
- vcpkg integrate install
- python -m pip install --user --upgrade pip
- "virtualenv --clear %VENV_DIR%"
- "%VENV_DIR%\\Scripts\\activate.bat"
- pip install --upgrade setuptools
- pip install tox
cache:
- C:\ProgramData\chocolatey\bin -> .appveyor.yml
- C:\ProgramData\chocolatey\lib -> .appveyor.yml
- C:\Tools\vcpkg\installed -> .appveyor.yml
before_build:
- mkdir BLD
- cd BLD
- cmake %VCPKG_INTEGRATION% -G "%CMAKE_GENERATOR%" %QPID_PROTON_CMAKE_ARGS% ..
- cd ..
build:
  project: BLD/Proton.sln
  parallel: true
  verbosity: normal
test_script:
- cd BLD
- cmake --build . --target install --config %CONFIGURATION%
- ctest -V -C %CONFIGURATION% %QPID_PROTON_CTEST_ARGS%
- cd ..
